version: "3.9"

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: clickstay-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin123}
      POSTGRES_DB: clickstay_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - clickstay-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clickstay-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Database
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-admin123}@db:5432/clickstay_db?connect_timeout=30&pool_timeout=30
      
      # NextAuth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      
      # Email (Optional)
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM:-Manuel Resort <noreply@manuelresort.com>}
      
      # PayMongo (Optional)
      PAYMONGO_SECRET_KEY: ${PAYMONGO_SECRET_KEY}
      PAYMONGO_PUBLIC_KEY: ${PAYMONGO_PUBLIC_KEY}
      PAYMONGO_WEBHOOK_SECRET: ${PAYMONGO_WEBHOOK_SECRET}
      
      # App Config
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      NODE_ENV: production
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - clickstay-network
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && node server.js"

networks:
  clickstay-network:
    driver: bridge

volumes:
  db_data:
    driver: local
